Update: Adds DDM test accounts in vets-api test accounts instructions.
department-of-veterans-affairs/vets-api-clients pull request #371
Opened 2022-11-21 19:59 UTC by Shoaib-VA

[API-20443]

2022-11-21 20:12 UTC, NCHLiberty commented
hi @Shoaib-VA This looks great. I would like to ask the DDM section to be moved up above the VV section so that the headings are listed alphabetically. Also, is it possibly to sit on this and not deploy the change until DDM is visible in the Sandbox/Prod Developer portal....release the change close in timing to when we deploy the API to production timing wise? That may be tomorrow or Wed or next week after the holiday freeze.

2022-11-22 15:22 UTC, NCHLiberty approved these changes

2022-12-09 18:20 UTC, dbrown-va requested changes
Since DDM does not have attended OAuth logins, this page is not applicable.

The DDM API can directly to it's supported test data page but the OAuth user logins (ID.me, Login.gov, etc.) are not applicable, only the calling ICN.

2023-02-16 00:35 UTC, dbrown-va commented
Closing as stale.

2023-02-16 00:35 UTC, closed without merging